name: Update Release notes

on:
  push:
    tags: ["v[0-9].[0-9]+.[0-9]+"]

defaults:
  run:
    shell: bash

jobs:
  update-release-notes:
    name: Update Release Notes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: |
          yarn install

      - name: Pack project
        run: |
          yarn run pack

      - name: Update changelog file
        run: |
          yarn commitizen init cz-conventional-changelog --save-dev --save-exact
          yarn conventional-changelog -p angular -i CHANGELOG.md -s

      - name: Commit and push updated CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add CHANGELOG.md
          git commit -m "chore: update changelog for $GITHUB_REF"
          git push origin main
